apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeease.fullname" . }}-admin
  labels:
    {{- include "homeease.labels" . | nindent 4 }}
    app: admin
spec:
  replicas: {{ .Values.replicaCount.adminBackend }}

  selector:
    matchLabels:
      {{- include "homeease.selectorLabels" . | nindent 6 }}
      app: admin

  template:
    metadata:
      labels:
        {{- include "homeease.selectorLabels" . | nindent 8 }}
        app: admin

    spec:
      containers:
        - name: admin-backend
          image: "{{ .Values.images.adminBackend.repository }}:{{ .Values.images.adminBackend.tag }}"
          imagePullPolicy: {{ .Values.images.adminBackend.pullPolicy }}

          ports:
            - name: http
              containerPort: 5001

          env:
            - name: NODE_ENV
              value: production

            - name: PORT
              value: "5001"

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeease.fullname" . }}-secrets
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeease.fullname" . }}-secrets
                  key: JWT_SECRET

            - name: ALLOWED_ORIGINS
              value: "*"

            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeease.fullname" . }}-secrets
                  key: EMAIL_USER

            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeease.fullname" . }}-secrets
                  key: EMAIL_PASS

            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeease.fullname" . }}-secrets
                  key: EMAIL_FROM

          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false

          resources:
            {{- toYaml .Values.resources.adminBackend | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 20
