{{- if not .Values.secrets.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homeease.fullname" . }}-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  EMAIL_USER: {{ .Values.secrets.emailUser | quote }}
  EMAIL_PASS: {{ .Values.secrets.emailPass | quote }}
  EMAIL_FROM: {{ .Values.secrets.emailFrom | quote }}
{{- end }}
