apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: {{ .Values.secrets.keyVault.secretProviderClass }}

spec:
  provider: azure

  parameters:

    usePodIdentity: "false"

    clientID: "{{ .Values.workloadIdentity.clientId }}"

    keyvaultName: "{{ .Values.keyVault.name }}"

    tenantId: "{{ .Values.keyVault.tenantId }}"

    objects: |
      array:
        - |
          objectName: MONGO-URI
          objectType: secret

        - |
          objectName: JWT-SECRET
          objectType: secret

        - |
          objectName: EMAIL-USER
          objectType: secret

        - |
          objectName: EMAIL-PASS
          objectType: secret

        - |
          objectName: EMAIL-FROM
          objectType: secret

  secretObjects:

    - secretName: {{ include "homeease.fullname" . }}-secrets
      type: Opaque

      data:
        - objectName: MONGO-URI
          key: MONGO_URI

        - objectName: JWT-SECRET
          key: JWT_SECRET

        - objectName: EMAIL-USER
          key: EMAIL_USER

        - objectName: EMAIL-PASS
          key: EMAIL_PASS

        - objectName: EMAIL-FROM
          key: EMAIL_FROM