apiVersion: v1
kind: ServiceAccount

metadata:
  name: homeease-workload-sa

  labels:
    app.kubernetes.io/name: homeease
    app.kubernetes.io/managed-by: Helm

  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.clientId }}"