{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homeease.fullname" . }}-app-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homeease.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.prometheusReleaseLabel }}

spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend
          - admin

  endpoints:
    - port: http
      path: /metrics
      interval: 15s

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}