images:
  backend:
    repository: acrhomeeasedev.azurecr.io/homeease-backend
    tag: ed899005e56349a539dda4d894bc6192244ab9e8
    pullPolicy: IfNotPresent

  adminBackend:
    repository: acrhomeeasedev.azurecr.io/homeease-admin-backend
    tag: ed899005e56349a539dda4d894bc6192244ab9e8
    pullPolicy: IfNotPresent

  frontend:
    repository: acrhomeeasedev.azurecr.io/homeease-frontend
    tag: c5d977f731c8bc9ca3c9e544025246d5b3bb0202
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: homeease.local

  tls:
    enabled: false
    clusterIssuer: letsencrypt-prod

monitoring:
  enabled: true
  prometheusReleaseLabel: kube-prometheus-stack