images:
  backend:
    repository: acrhomeeasedev.azurecr.io/homeease-backend
    tag: 3cbd5224e67ad070a71d374198c32f14fe482e99
    pullPolicy: IfNotPresent

  adminBackend:
    repository: acrhomeeasedev.azurecr.io/homeease-admin-backend
    tag: 3cbd5224e67ad070a71d374198c32f14fe482e99
    pullPolicy: IfNotPresent

  frontend:
    repository: acrhomeeasedev.azurecr.io/homeease-frontend
    tag: c5d977f731c8bc9ca3c9e544025246d5b3bb0202
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: homeease.local

  tls:
    enabled: false
    clusterIssuer: letsencrypt-prod

monitoring:
  enabled: true
  prometheusReleaseLabel: kube-prometheus-stack